export default [
    {
        id:0,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Eggs" ,
        imageUrl: "https://i.etsystatic.com/24469543/r/il/56f620/2653831971/il_794xN.2653831971_s22q.jpg",
    },
    {
        id:1,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Exotic Eggs" ,
        imageUrl: "https://image.shutterstock.com/image-photo/quail-eggs-260nw-279272417.jpg",
    },
    {
        id:2,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Local Eggs" ,
        imageUrl: "https://newengland.com/wp-content/uploads/2014/07/eggs-dt-720x480.jpg",
    },
    {
        id:3,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Milk" ,
        imageUrl: "https://www.greenqueen.com.hk/wp-content/uploads/2020/01/turtletree-labs.jpg",
    },
    {
        id:4,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Nile Perch" ,
        imageUrl: "https://www.eurofoodlink.com/wp-content/uploads/2019/01/Nile-Perch-1024x346-1024x346.jpeg",
    },
    {
        id:5,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Processed Honey" ,
        imageUrl: "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/324966_2200-1200x628.jpg",
    },
    {
        id:6,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Tilapia" ,
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Oreochromis-niloticus-Nairobi.JPG",
    },
    {
        id:7,
        commoditycat: "Animal Products",
        SubCategory: "Animal Products - Other",
        commodityproduct:"Unprocessed Honey" ,
        imageUrl: "https://draxe.com/wp-content/uploads/2018/08/Raw-Honey_HEADER.jpg",
    },
    {
        id:8,
        commoditycat: "Animal Products",
        SubCategory: "Livestock",
        commodityproduct:"Beef" ,
        imageUrl: "https://challengedairy.com/sites/default/files/recipe/images/recipe_roast_beef_with_tangy_mustard_sauce_2280.jpg",
    },
    {
        id:9,
        commoditycat: "Animal Products",
        SubCategory: "Livestock",
        commodityproduct:"Goat Meat" ,
        imageUrl: "https://static.toiimg.com/thumb/msid-48216452,width-1070,height-580,overlay-toi_sw,pt-32,y_pad-40,resizemode-75,imgsize-61583/48216452.jpg",
    },
    {
        id:10,
        commoditycat: "Animal Products",
        SubCategory: "Livestock",
        commodityproduct:"Pork" ,
        imageUrl: "https://www.thespruceeats.com/thmb/R_l40GgQJESQO4pEuas5kCkNkTU=/3000x2000/filters:fill(auto,1)/foolproof-slow-roasted-pork-shoulder-recipe-995300-hero-01-b6f9d889a0cf4189acad5faaba7f95b1.jpg",
    },
    {
        id:11,
        commoditycat: "Animal Products",
        SubCategory: "Poultry",
        commodityproduct:"Exotic Chicken" ,
        imageUrl: "https://i.pinimg.com/originals/b0/ec/44/b0ec443d4fa070ccf503422a151ebe9a.jpg",
    },
  ];
  